---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sgmcjnpl/public_html/143
    - /bin/rsync -av --exclude='.git' --exclude='node_modules' --exclude='.env' --exclude='storage/app/public' . $DEPLOYPATH/
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:clear
    - cd $DEPLOYPATH && php artisan storage:link --force
